site_name: SqlIntuitive
site_description: Project documentation
site_author: Moritz Bauer (einfachIrgendwer0815)

repo_url: https://github.com/einfachIrgendwer0815/SqlIntuitive
edit_uri: ""

nav:
  - Home: 'index.md'
  - 'Getting started': 'gettingStarted.md'
  - 'User Guide':
    - 'Overview': 'userGuide/overview.md'

  - 'Code docs':
    - 'Overview': 'codeDocs/overview.md'

  - 'Changelog': 'changelog.md'
